import type { ComponentPropsWithoutRef, ComponentType } from "react"
// Named imports keep the generated 5k-icon modules tree-shakeable — only the
// icons listed here end up in the bundle.
import {
    AdjustmentsHorizontalIcon,
    AlertCircleIcon,
    AppsIcon,
    ArrowsExchangeIcon,
    ArrowsTransferUpDownIcon,
    BoltIcon,
    Book2Icon,
    BuildingBankIcon,
    BuildingIcon,
    BuildingSkyscraperIcon,
    BuildingStoreIcon,
    BuildingWarehouseIcon,
    CalendarIcon,
    CalendarMonthIcon,
    CashBanknoteIcon,
    CashRegisterIcon,
    Category2Icon,
    ChartBarIcon,
    ChartDotsIcon,
    CheckIcon,
    ChecklistIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    CircleIcon,
    CircleMinusIcon,
    ClipboardCheckIcon,
    ClipboardListIcon,
    ClockIcon,
    CoinOffIcon,
    CreditCardIcon,
    CurrencyDollarIcon,
    DeviceDesktopDollarIcon,
    ExternalLinkIcon,
    FileInvoiceIcon,
    FileTextIcon,
    HelpCircleIcon,
    Hierarchy2Icon,
    HierarchyIcon,
    HistoryIcon,
    HourglassIcon,
    InfoCircleIcon,
    KeyIcon,
    LayoutGridIcon,
    ListDetailsIcon,
    LockIcon,
    LogoutIcon,
    Menu2Icon,
    PackageExportIcon,
    PackageIcon,
    PackageImportIcon,
    PackagesIcon,
    PencilIcon,
    PercentageIcon,
    PigMoneyIcon,
    PlusIcon,
    PrinterIcon,
    PuzzleIcon,
    QrcodeIcon,
    Receipt2Icon,
    ReceiptIcon,
    RefreshIcon,
    ReportAnalyticsIcon,
    RosetteDiscountIcon,
    RotateClockwiseIcon,
    RulerMeasureIcon,
    ScaleIcon,
    SearchIcon,
    SearchOffIcon,
    SettingsAutomationIcon,
    SettingsCogIcon,
    SettingsIcon,
    ShieldXIcon,
    TagIcon,
    TagsIcon,
    TransferIcon,
    TrashIcon,
    TrashXIcon,
    TrendingUpIcon,
    UserCogIcon,
    UsersGroupIcon,
    WalletIcon,
    XIcon,
} from "@/components/icons/outline"
import {
    AlertCircleFilledIcon,
    AlertTriangleFilledIcon,
    CircleCheckFilledIcon,
    CircleXFilledIcon,
} from "@/components/icons/solid"

export type IconName = string

type IconSvgProps = ComponentPropsWithoutRef<"svg"> & {
    size?: number | string
    strokeWidth?: number | string
}
type IconComponent = ComponentType<IconSvgProps>

const icons: Record<string, IconComponent> = {
    account_balance: BuildingBankIcon,
    account_balance_wallet: WalletIcon,
    account_tree: HierarchyIcon,
    add: PlusIcon,
    apps: AppsIcon,
    arrow_drop_down: ChevronDownIcon,
    attach_money: CurrencyDollarIcon,
    balance: ScaleIcon,
    bar_chart: ChartBarIcon,
    block: ShieldXIcon,
    bolt: BoltIcon,
    business: BuildingIcon,
    calendar_month: CalendarMonthIcon,
    calendar_today: CalendarIcon,
    cancel: CircleXFilledIcon,
    card_membership: CreditCardIcon,
    category: Category2Icon,
    check: CheckIcon,
    check_circle: CircleCheckFilledIcon,
    chevron_left: ChevronLeftIcon,
    chevron_right: ChevronRightIcon,
    close: XIcon,
    corporate_fare: BuildingSkyscraperIcon,
    delete: TrashIcon,
    delete_forever: TrashXIcon,
    description: FileTextIcon,
    edit: PencilIcon,
    error: AlertCircleFilledIcon,
    error_outline: AlertCircleIcon,
    expand_less: ChevronUpIcon,
    expand_more: ChevronDownIcon,
    extension: PuzzleIcon,
    fact_check: ClipboardCheckIcon,
    format_list_bulleted: ListDetailsIcon,
    grid_view: LayoutGridIcon,
    groups: UsersGroupIcon,
    history: HistoryIcon,
    hourglass_empty: HourglassIcon,
    info: InfoCircleIcon,
    insights: ChartDotsIcon,
    inventory_2: PackageIcon,
    key: KeyIcon,
    list_alt: ClipboardListIcon,
    local_offer: TagIcon,
    lock: LockIcon,
    logout: LogoutIcon,
    manage_accounts: UserCogIcon,
    menu: Menu2Icon,
    menu_book: Book2Icon,
    money_off: CoinOffIcon,
    open_in_new: ExternalLinkIcon,
    payments: CashBanknoteIcon,
    pending: ClockIcon,
    percent: PercentageIcon,
    point_of_sale: DeviceDesktopDollarIcon,
    pos_terminal: CashRegisterIcon,
    print: PrinterIcon,
    qr_code_2: QrcodeIcon,
    radio_button_unchecked: CircleIcon,
    receipt: ReceiptIcon,
    receipt_long: Receipt2Icon,
    remove_circle: CircleMinusIcon,
    reports: ReportAnalyticsIcon,
    request_quote: FileInvoiceIcon,
    restart_alt: RotateClockwiseIcon,
    rule: ChecklistIcon,
    savings: PigMoneyIcon,
    search: SearchIcon,
    search_off: SearchOffIcon,
    sell: TagsIcon,
    settings: SettingsIcon,
    settings_2: SettingsCogIcon,
    settings_suggest: SettingsAutomationIcon,
    shifts: ClockIcon,
    storefront: BuildingStoreIcon,
    straighten: RulerMeasureIcon,
    swap_horiz: ArrowsExchangeIcon,
    sync_alt: RefreshIcon,
    trending_up: TrendingUpIcon,
    tune: AdjustmentsHorizontalIcon,
    warehouse: BuildingWarehouseIcon,
    warning: AlertTriangleFilledIcon,

    inventory_adjustment: AdjustmentsHorizontalIcon,
    inventory_brands: TagsIcon,
    inventory_categories: Hierarchy2Icon,
    inventory_issue: PackageExportIcon,
    inventory_movements: ArrowsTransferUpDownIcon,
    inventory_pricing: TagIcon,
    inventory_product_units: QrcodeIcon,
    inventory_products: PackageIcon,
    inventory_promotions: RosetteDiscountIcon,
    inventory_receipt: PackageImportIcon,
    inventory_stock: BuildingWarehouseIcon,
    inventory_stock_lots: PackagesIcon,
    inventory_transfer: TransferIcon,
    inventory_units: RulerMeasureIcon,
    inventory_variant_groups: Category2Icon,
    inventory_variants: AdjustmentsHorizontalIcon,
}

interface IconProps extends IconSvgProps {
    name: IconName
}

export function Icon({ name, size = 24, className = "", ...props }: IconProps) {
    const Component = icons[name] ?? HelpCircleIcon

    return <Component {...props} aria-hidden="true" className={`inline-block select-none align-middle ${className}`} size={size} />
}
