import {
    AppWindow,
    ArrowDownWideNarrow,
    BadgeDollarSign,
    BadgePercent,
    Banknote,
    BarChart3,
    BookOpen,
    Building2,
    Calendar,
    ChartColumnIncreasing,
    Check,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    CircleAlert,
    CircleDollarSign,
    CircleHelp,
    CircleOff,
    CircleX,
    Circle,
    ClipboardCheck,
    ClipboardClock,
    ClipboardList,
    Clock,
    FileCheck2,
    FileText,
    Grid2X2,
    History,
    Hourglass,
    Info,
    KeyRound,
    Landmark,
    LibraryBig,
    List,
    Lock,
    LogOut,
    Menu,
    MonitorCog,
    NotebookText,
    Package,
    Percent,
    Plus,
    Printer,
    Receipt,
    ReceiptText,
    RotateCcw,
    Search,
    SearchX,
    Settings,
    Settings2,
    ShieldX,
    SlidersHorizontal,
    Store,
    Tags,
    Trash2,
    TrendingUp,
    UserCog,
    UsersRound,
    Wallet,
    Warehouse,
    X,
    Zap,
} from "lucide-react"
import { cloneElement, type ComponentPropsWithoutRef, type ComponentType, type ReactElement } from "react"
import * as TablerOutlineIcons from "@/components/icons/outline.jsx"

export type IconName = string

type IconComponent = ComponentType<ComponentPropsWithoutRef<"svg"> & { size?: number }>
type GeneratedTablerIcon = (props: { className?: string; strokeWidth?: number }) => ReactElement<ComponentPropsWithoutRef<"svg">>
const tablerOutlineIcons = TablerOutlineIcons as Record<string, GeneratedTablerIcon>

function tablerIcon(Component: GeneratedTablerIcon): IconComponent {
    return function TablerIcon({ className, strokeWidth = 1.5, size = 24, ...props }) {
        const numericStrokeWidth = typeof strokeWidth === "number" ? strokeWidth : Number(strokeWidth) || 1.5
        const element = <Component className={className} strokeWidth={numericStrokeWidth} />

        return cloneElement(element, {
            ...props,
            className,
            width: size,
            height: size,
            strokeWidth: numericStrokeWidth,
        })
    }
}

const icons: Record<string, IconComponent> = {
    account_balance: Landmark,
    account_balance_wallet: Wallet,
    account_tree: LibraryBig,
    add: Plus,
    apps: AppWindow,
    arrow_drop_down: ChevronDown,
    attach_money: CircleDollarSign,
    balance: ArrowDownWideNarrow,
    bar_chart: BarChart3,
    block: ShieldX,
    bolt: Zap,
    business: Building2,
    calendar_month: Calendar,
    calendar_today: Calendar,
    cancel: CircleX,
    card_membership: BadgePercent,
    check: Check,
    check_circle: CheckCircle2,
    chevron_left: ChevronLeft,
    chevron_right: ChevronRight,
    close: X,
    corporate_fare: Building2,
    delete: Trash2,
    delete_forever: Trash2,
    description: FileText,
    edit: FileCheck2,
    error: CircleAlert,
    error_outline: CircleAlert,
    extension: AppWindow,
    fact_check: ClipboardCheck,
    format_list_bulleted: List,
    grid_view: Grid2X2,
    groups: UsersRound,
    history: History,
    hourglass_empty: Hourglass,
    info: Info,
    key: KeyRound,
    insights: BarChart3,
    inventory_2: Package,
    list_alt: ClipboardList,
    local_offer: Tags,
    lock: Lock,
    logout: LogOut,
    menu: Menu,
    manage_accounts: UserCog,
    menu_book: BookOpen,
    money_off: CircleOff,
    open_in_new: AppWindow,
    payments: Banknote,
    pending: Clock,
    percent: Percent,
    point_of_sale: BadgeDollarSign,
    pos_terminal: MonitorCog,
    receipt: Receipt,
    receipt_long: ReceiptText,
    print: Printer,
    request_quote: NotebookText,
    restart_alt: RotateCcw,
    radio_button_unchecked: Circle,
    rule: ClipboardCheck,
    savings: Landmark,
    search: Search,
    search_off: SearchX,
    sell: Tags,
    settings: Settings,
    settings_2: Settings2,
    settings_suggest: Settings,
    shifts: ClipboardClock,
    storefront: Store,
    tune: SlidersHorizontal,
    reports: ChartColumnIncreasing,
    trending_up: TrendingUp,
    warehouse: Warehouse,
    warning: CircleAlert,

    inventory_adjustment: tablerIcon(tablerOutlineIcons.RefreshIcon),
    inventory_brands: tablerIcon(tablerOutlineIcons.TagsIcon),
    inventory_categories: tablerIcon(tablerOutlineIcons.Hierarchy2Icon),
    inventory_issue: tablerIcon(tablerOutlineIcons.CircleMinusIcon),
    inventory_movements: tablerIcon(tablerOutlineIcons.HistoryIcon),
    inventory_pricing: tablerIcon(tablerOutlineIcons.TagIcon),
    inventory_product_units: tablerIcon(tablerOutlineIcons.QrcodeIcon),
    inventory_products: tablerIcon(tablerOutlineIcons.PackageIcon),
    inventory_promotions: tablerIcon(tablerOutlineIcons.PercentageIcon),
    inventory_receipt: tablerIcon(tablerOutlineIcons.Receipt2Icon),
    inventory_stock: tablerIcon(tablerOutlineIcons.BuildingWarehouseIcon),
    inventory_stock_lots: tablerIcon(tablerOutlineIcons.TagIcon),
    inventory_transfer: tablerIcon(tablerOutlineIcons.ArrowsExchangeIcon),
    inventory_units: tablerIcon(tablerOutlineIcons.RulerMeasureIcon),
    inventory_variant_groups: tablerIcon(tablerOutlineIcons.Category2Icon),
    inventory_variants: tablerIcon(tablerOutlineIcons.AdjustmentsHorizontalIcon),

    qr_code_2: tablerIcon(tablerOutlineIcons.QrcodeIcon),
    remove_circle: tablerIcon(tablerOutlineIcons.CircleMinusIcon),
    straighten: tablerIcon(tablerOutlineIcons.RulerMeasureIcon),
    swap_horiz: tablerIcon(tablerOutlineIcons.ArrowsExchangeIcon),
    sync_alt: tablerIcon(tablerOutlineIcons.RefreshIcon),
}

interface IconProps extends ComponentPropsWithoutRef<"svg"> {
    name: IconName
    size?: number
}

export function Icon({ name, size = 24, className = "", ...props }: IconProps) {
    const Component = icons[name] ?? CircleHelp

    return <Component {...props} aria-hidden="true" className={`inline-block select-none align-middle ${className}`} size={size} />
}
